### ISSUE TITLE
Fix insertion sort

### ISSUE THREAD

**Issue by yasenAlexiev** [AlexStoyanova/OOP-FMI#2]
[https://github.com/AlexStoyanova/OOP-FMI/blob/master/Structures_Tasks_From_Kr/Structures_Tasks_From_Kr/main.cpp#L58](url)

You must have helper varible to save arr[i].fn and lets call it 'key'. Second loop condition must have key > arr[j].fn, because if you iterate to zero every time, you reach every time worst case O(n^2). And swap element after second loop, when you hind right position for him.
Also you can swap two stundets with std::swap like that: std::swap(arr[i], arr[j]). That works because std::swap is template function, but that's early for you.

**Comment by AlexStoyanova** [comment]
Thanks! :100:
